### PR TITLE
Add hint for Sumatra PDF

### PR DESCRIPTION
**Pull request by koppor**
I am on Windows and using SumatraPDF. It is not directly explained how the `tex` synchronization works, I thought, it would be a good idea to place the howto here to provide a self-contained documentation and to save time for ltx2any users.

### CODE REVIEW

**Comment by reitzig** [comment]
Hum. I don't think adding documentation for *all* the PDF viewers and OSs is feasible. I think I'll add a broader note that the user system may have to be reconfigured so the links actually open. I expect googling "[viewer] open link text file" or similar should lead to the required instructions.

**Comment by koppor** [comment]
Sumatra PDF is *the* standard PDF viewer for LaTeX users on Windows. It's open source and deserves to be promoted. The thing is that I googled for that string and landed on a newsgroup pointing to code.google.com and from there to a non existing file, because code.google.com is in ARCHIVE mode. I had to search for myself for the file and think about how to tweak it.

**Comment by reitzig** [comment]
That's all very fine, but it's still not a piece of documentation for *this* tool. I guess a Wiki page for hints about setting up related tools maybe okay.

That said, you can ask and self-answer a question about this on [Super User Stack Exchange](http://superuser.com/) so future Googlers have more access.

**Comment by akerbos** [comment]
I have reserved room on the [installation wiki page](https://github.com/akerbos/ltx2any/wiki) for things like this. Do you have a write-up for Sumatra somewhere?

**Comment by koppor** [comment]
I wrote a quick tutorial at https://github.com/akerbos/ltx2any/wiki#sumatrapdf.

I could stand to add a link to http://tex.stackexchange.com/questions/339/latex-editors-ides, even though the link rocks :8ball:

**Comment by akerbos** [comment]
Great, thanks!

**Pull request closed without merging**
